### ISSUE TITLE
Failed to connect to Google Translate. trying again... 

### ISSUE THREAD

**Issue by trevorf999** [horihiro/esp8266-google-tts#12]
Hi,

I am getting the following message below when running the example. Other devices have access Google Translate, and ESP has no problems getting data from web in other sketches.

........
Connected to back.gate.sases_XXXXX
IP address: 192.168.XXX.XXX
Failed to connect to Google Translate. trying again...  (current: 0, maxRetry: 10)
Failed to connect to Google Translate. trying again...  (current: 1, maxRetry: 10)
Failed to connect to Google Translate. trying again...  (current: 2, maxRetry: 10)
Failed to connect to Google Translate. trying again...  (current: 3, maxRetry: 10)
Failed to connect to Google Translate. trying again...  (current: 4, maxRetry: 10)
Failed to connect to Google Translate. trying again...  (current: 5, maxRetry: 10)
Failed to connect to Google Translate. trying again...  (current: 6, maxRetry: 10)
Failed to connect to Google Translate. trying again...  (current: 7, maxRetry: 10)

**Comment by horihiro** [comment]
This module is based on `TKK` parameter on Google Translate.
Google might close old algorithm, which uses `TKK` parameter, on the page.

**Comment by horihiro** [comment]
`/translate_tts` which this library accesses returns 404.
![image](https://user-images.githubusercontent.com/4566555/101269060-cb067500-37ad-11eb-87dd-0a5844f23c13.png)

**Comment by horihiro** [comment]
https://github.com/Boudewijn26/gTTS-token/blob/master/docs/november-2020-translate-changes.md

**Comment by horihiro** [comment]
Please try 1.0.10
https://www.arduinolibraries.info/libraries/esp8266-google-tts

This version doesn't try to connect to Google Translate.

**Comment by Qbunjo** [comment]
Hi horihiro, I just checked new version of your library - now it works! Thanks for your effort!

**Comment by horihiro** [comment]
close this
