### ISSUE TITLE
Send It To Decoder Board

### ISSUE THREAD

**Issue by podaen** [horihiro/esp8266-google-tts#18]
how can I send it to a board like this

![2021-10-13_000307](https://user-images.githubusercontent.com/63886347/137604657-9ab726aa-4a9a-4a71-b2a1-2be939a3d43f.jpg)

That is connected by I2S. Like this...

//DAC	ESP32
//-----------------
//VDD		5V
//3.3V		 /
//GND		GND
//DIN		OUT (GPIO22)
//L/R		GND
//LCK		WS (GPIO25)
//BLK		BCK (GPIO26)
//FMT		GND
//XMT		3V

**Comment by horihiro** [comment]
I'm not sure if your question is regarding **this library**.
