### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by mc9625** [horihiro/esp8266-google-tts#3]
I'm afraid Google has changed something. Right now that library doesn't seem working! Not for me at least! :(

**Comment by horihiro** [comment]
It seems that code for creating token on Google Translate is changed drastically.

It may take long time to fix it.
Sorry.

**Comment by horihiro** [comment]
A root cause of this issue is same as [this](https://github.com/zlargon/google-tts/pull/14)

**Comment by horihiro** [comment]
I released fixed version (1.0.6) just now.
Please wait until Arduino Library Manager picks up this version.

**Comment by horihiro** [comment]
Hi @mc9625 
Could you please try version 1.0.6?
Thanks

**Comment by horihiro** [comment]
Please re-open this issue if it doesn't work yet.

**Comment by yngsoftwaredev** [comment]
I have tried version 1.0.6 and it just chimes, doesn't say anything even using the example sketches provided. Thoughts? It isn't saying any error messages either, but I imagine that would only be if one was provided.
