### ISSUE TITLE
Version 1.0.6 chimes, no speech?

### ISSUE THREAD

**Issue by yngsoftwaredev** [horihiro/esp8266-google-tts#4]
_Originally posted by @yngsoftwaredev in https://github.com/horihiro/esp8266-google-tts/issues/3#issuecomment-442891129_

I have tried version 1.0.6 and it just chimes, doesn't say anything even using the example sketches provided. Thoughts? It isn't saying any error messages either, but I imagine that would only be if one was provided.

**Comment by horihiro** [comment]
I will investigate about this issue.
please wait for several days.

**Comment by horihiro** [comment]
Maybe google translate page has changed.
i should fix such as https://github.com/zlargon/google-tts/commit/a0f6ffaf9fd0f5f5dd544f3a226e784687dc92fc

**Comment by horihiro** [comment]
I released 1.0.7.
Please check the tweets by https://twitter.com/arduinolibs

If this release has no problem in your validadtion, please close this issue.

**Comment by horihiro** [comment]
it's released.

https://www.arduinolibraries.info/libraries/esp8266-google-tts

**Comment by yngsoftwaredev** [comment]
I will test and let you know. thanks

**Comment by yngsoftwaredev** [comment]
Works like a charm! Thanks
