### ISSUE TITLE
Now it does not work

### ISSUE THREAD

**Issue by NoratorLab** [horihiro/esp8266-google-tts#6]
Great job! It used to work fine! But now it does not work. Maybe Google changed something?

**Comment by horihiro** [comment]
Thanks @Colobox

I confirmed that this library worked fine at 2019-03-03T21:40Z .

Does this issue continue now on your side?

**Comment by horihiro** [comment]
And it works fine now (2019-03-04T10:20Z).

Could you please check it again?

**Comment by NoratorLab** [comment]
I'll check it again.

**Comment by horihiro** [comment]
Does it work on your device?

**Comment by NoratorLab** [comment]
Sorry, I have not had the opportunity to check.

**Comment by NoratorLab** [comment]
Problem still exists. When I run the example, it returns:
connection failed
_ERROR
A few weeks ago worked fine!
I checked everything. What am I doing wrong?

**Comment by horihiro** [comment]
Thanks @Colobox

The error raised at following line.

https://github.com/horihiro/esp8266-google-tts/blob/64f4b4675928f258a45ae1ca7f986a93f28951d8/src/google-tts.cpp#L101

So your device cannot connect to google translate page, not page parsing error.

Could you please let me know if your device can connect to `https://translate.google.com` using only WifiClientSecure , not this library?

**Comment by NoratorLab** [comment]
I tested the following code and it returns "Connection failed":

#include <ESP8266WiFi.h>
#include <WiFiClientSecure.h>

const char *ssid = "<REPLASE_YOUR_WIFI_SSID>";
const char *password = "<REPLASE_YOUR_WIFI_PASSWORD>";

const char* host = "translate.google.com";
const int httpsPort = 443;

void setup()
{
  Serial.begin(115200);
  Serial.println();

  Serial.println("Connecting to WiFi");
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED)
  {
    Serial.print(".");
    delay(250);
  }
  Serial.println();
  Serial.print("Connected to ");
  Serial.println(ssid);

  WiFiClientSecure client;
  Serial.print("Connecting to ");
  Serial.println(host);
  if (!client.connect(host, httpsPort))
  {
    Serial.println("Connection failed");
    return;
  }
  Serial.println("Connection Ok");
}

void loop()
{
}

**Comment by horihiro** [comment]
According to the result of your test, it seems that this issue is not due to this library because your device cannot connect the page.

I recommend you to check connectivity to other sites using same and/or other device.

**Comment by NoratorLab** [comment]
I added to my sketch above:

const char fingerprint[] PROGMEM = "f8 1e 31 71 fa 08 5b c0 4c 83 b6 64 4b 9f 22 9f 0c ba 8e 57";

and:

client.setFingerprint(fingerprint);

after WiFiClientSecure client.

Now everything works: Connection Ok
How can I do the same for your library?

**Comment by horihiro** [comment]
There is no option to set fingerprint in this library, because I haven't seen this behavior.

And I cannot fix this issue as same reason.

You can fork this repo if you want to fix this.

**Comment by NoratorLab** [comment]
Thanks for help very much!
I see in your file "google-tts.h":
#define FINGERPRINT_GTRANS "51:95:BF:29:CC:79:4B:FE:E2:0B:0F:EA:B5:95:1B:5A:0A:91:AB:39"
But it is not used in this file and in the "google-tts.cpp". Unfortunately I could not find.
Some time ago I used WiFiClientSecure  in my sketches without a fingerprint, but now I can't.  My sketches work only with a fingerprint now.
Is it necessary to use a fingerprint with WiFiClientSecure in all cases?
What happens when a fingerprint is not valid after some time?

**Comment by horihiro** [comment]
I don't have any information about changing in WifiClientSecure.

You can create issue at https://github.com/esp8266/Arduino/issues in order to know what happened.

**Comment by NoratorLab** [comment]
Thanks!

**Comment by NoratorLab** [comment]
I understood what was the matter.
The library works with the old version 2.4.2 of  the "ESP8266 core for Arduino", but does not work with the new version 2.5.0.
I checked it.

**Comment by horihiro** [comment]
Sorry for my late reply.
And thank for your investigation.

But I can't use arduino core 2.5.0 now due to some reasons.
Please use 2.4.2 or before.

I will update documents.

**Comment by Colobox** [comment]
Thanks!

**Comment by NoratorLab** [comment]
Thanks!

**Comment by reaper7** [comment]
You can try this solution:

![zmiany](https://user-images.githubusercontent.com/4134851/55397298-34989f80-5546-11e9-9217-f8a631e6276b.jpg)

You have 2 options
1 - pass new fingerprint to bearssl lib
2 - use insecure option

check on my github:
https://github.com/reaper7/esp8266-google-tts

I can do PR, but I do not know if these changes will work well in the old environment

**Comment by NoratorLab** [comment]
Thanks very much!

**Comment by horihiro** [comment]
I committed the code for esp8266 sdk 2.5.0 compatible to this repository yesterday (not released ).
You can try this code if you want.

Thanks

**Comment by NoratorLab** [comment]
Thanks!
