### ISSUE TITLE
connection failed _ERROR

### ISSUE THREAD

**Issue by deladriere** [horihiro/esp8266-google-tts#7]
Did Google change something ?
I can connect to my network but it returns an error

`Connected to ******
IP address: 192.168.1.41
connection failed
_ERROR
connection failed
_ERROR
`

**Comment by horihiro** [comment]
Hmm...
In my environment, it can get an mp3 URL without any problem.

And this library connects to only google, not Google Home.
So the message was written by other library such as esp8266-google-home-notifier.

**Comment by deladriere** [comment]
Ok thanks
I thought I would also read the audio ... So it gives only the URL back ?

**Comment by horihiro** [comment]
yes, this library just gets tts mp3 url from google tranlate.
what tries to connect to google home is other library you are using.
