### ISSUE TITLE
connection failed

### ISSUE THREAD

**Issue by pvdw0310** [horihiro/esp8266-google-tts#8]
Hi, 
I just tried the sketch in the library and I get an error: do you have any idea what went wrong?

IP address: 192.168.1.49
connection failed
_ERROR
connection failed
_ERROR

Thanks.
Peter

**Comment by Qbunjo** [comment]
I've got the same error.

**Comment by horihiro** [comment]
I think it is a transient issue.
how often does it happen?

**Comment by pvdw0310** [comment]
I get it always.

**Comment by pvdw0310** [comment]
But I using esp8266, I wrote someware that it only works fine on a esp32? Is esp8266 a problem?

**Comment by horihiro** [comment]
no, it can work on esp8266. 
i can make it work using both

**Comment by pvdw0310** [comment]
The title is esp8266-google-tts. So I think it is also for the esp8266. It would be nice if it can work on the esp8266. Let me know if you finnish the adaptation for the esp8266.
Thanks

**Comment by Qbunjo** [comment]
I also have problem with this code. It looks like Google changed the URL.

niedz., 24 maj 2020, 13:38 użytkownik pvdw0310 <notifications@github.com>
napisał:

**Comment by horihiro** [comment]
I don't think the URL is changed because I confirmed that this library on ESP8266 works fine now.

**Comment by pvdw0310** [comment]
Thanks alot, I will try it next week.

**Comment by Qbunjo** [comment]
Ok, I'm gonna check on that.

niedz., 24 maj 2020, 14:02 użytkownik horihiro <notifications@github.com>
napisał:

**Comment by Qbunjo** [comment]
Well, I just uploaded your example sketch to ESP8266 and the error still happens.


IP address: 192.168.0.188
connection failed
_ERROR
connection failed
_ERROR

I also checked it on ESP32 - and it works.

**Comment by horihiro** [comment]
Please try 1.0.10
https://www.arduinolibraries.info/libraries/esp8266-google-tts

This version doesn't try to connect to Google Translate.
