### ISSUE TITLE
Failed to get TTS url.

### ISSUE THREAD

**Issue by gopalram84** [horihiro/esp8266-google-tts#9]
23:46:22.947 -> connection failed
23:46:22.980 -> Failed to get TTS url.

i am using esp8266 , please help me

**Comment by horihiro** [comment]
Please check if your esp8266 can connect to internet, especially Google Translate page.

**Comment by horihiro** [comment]
Please try 1.0.10
https://www.arduinolibraries.info/libraries/esp8266-google-tts

This version doesn't try to connect to Google Translate.
